### ISSUE TITLE
Erro Eslint CRLF

### ISSUE THREAD

**Issue by CaaioSB** [naveteam/react-boilerplate#34]
**Problema ocorrido**
Ao executar o comando "npm creat-nave-app _my-project_" foi feita uma clonagem do repositório "react-boilerplate", porém, o maior problema foi o seguinte [erro](https://imgur.com/PdUcX7Y)

**Para reproduzir**
Siga as etapas abaixo:

1. Clone o boilerplate a partir do comando: `npm create-nave-app my-app`
2. Acesse no diretório do boilerplate: `cd my-app`
3. Execute o comando: `yarn start`
4. Veja o erro.

**Expectativa**
Que no console não contenha erros e o site execute normalmente renderizando a página de login.

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser: [Chrome]
- Version: [83.0.4103.116 (Versão oficial) 64 bits]

**Possível resolução**
Eu obtive bons resultados fazendo a alteração da seguinte linha do arquivo [.eslintrc.json](https://github.com/naveteam/react-boilerplate/blob/master/.eslintrc.json).
```json
"prettier/prettier": 2,
```

Para

```
"prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
 ],
```

**Comment by eduardobittencourt** [comment]
Fala Caio! Tudo bem?

O controle do tipo de quebra de linha é feito no arquivo `.editorconfig`, mas pra que ele funcione vc precisa ter a extensão do editorconfig instalada no teu editor (no caso do vscode é essa [aqui](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)).

Confirma pra nós por favor que a extensão está instalada e ativa no teu editor por favor? Valeu!

**Comment by CaaioSB** [comment]
Saudações Eduardo,

Pois então, de primeira intância eu até suspeitei ser isto, e então lembrei que no meu ambiente Windows eu não tinha todas extensões instaladas, então fiz a instalação delas (inclusive do EditorConfig), porém, ao desfazer as minhas alterações, o projeto continua a dar o erro.

Segue como anexo.
![image](https://user-images.githubusercontent.com/34246280/87842631-157d6880-c884-11ea-988f-6b1866587701.png)

**Comment by eduardobittencourt** [comment]
Opa, então parece ser algo relacionado ao eslint/prettier mesmo, bem visto!

Se vc adicionar a linha `"endOfLine": "auto"` no arquivo `.prettierrc.json` o projeto volta a funcionar pra vc? Caso sim, já podemos abrir um PR com essa alteração.

**Comment by CaaioSB** [comment]
@eduardobittencourt  infelizmente não resolveu com essa sua dica, continuou a dar o mesmo erro.

Até o momento a única solução que funcionou para mim é a que foi mencionada no corpo da Issue (editar o arquivo[ eslintrc.json](https://github.com/naveteam/react-boilerplate/blob/master/.eslintrc.json)).

**Comment by CaaioSB** [comment]
@eduardobittencourt neste momento eu fiz os mesmos procedimentos em um ambiente Linux, e o projeto não apresentou quaisquer erro, rodou tanto com o código original quanto com a alteração que eu fiz no ambiente Windows.
Então assimilamos que o problema não está no projeto, e sim no ambiente, acredito que realmente falta configurar alguma extensão por exemplo.

**Comment by eduardobittencourt** [comment]
Bem observado! Pode ser algo relacionado ao ambiente sim... Vamos tentar alinhar as configurações pra ver se isso ajuda.

Nós utilizamos apenas duas extensões para formatar nosso código: [Editorconfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) e [Eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

Tendo elas instaladas, no teu arquivo `settings.json` do vscode precisamos dessas configurações: 

```
...
"editor.codeActionsOnSave": {
        "source.fixAll": true
    },
"eslint.enable": true,
"eslint.alwaysShowStatus": true,
...
```

Se com essas configurações o ambiente ainda não funcionar no Windows, provavelmente falte sim alguma informação a mais no nosso boilerplate que equalize a quebra de linha entre os ambientes.

**Comment by jpbretanha** [comment]
Fala @CaaioSB! Esse erro só ocorre no windows mesmo. Já tínhamos encontrado esse problema em um outro teste que fiz no meu computador rodando no windows também. Ainda não temos uma resolução, mas parece que é relacionado ao prettier mesmo.

**Comment by CaaioSB** [comment]
> Fala @CaaioSB! Esse erro só ocorre no windows mesmo. Já tínhamos encontrado esse problema em um outro teste que fiz no meu computador rodando no windows também. Ainda não temos uma resolução, mas parece que é relacionado ao prettier mesmo.

Olá @jpbretanha, eu ainda não tive tempo para realizar essa última dica do @eduardobittencourt, logo após eu realizar os testes eu deixo um feedback.

**Comment by CaaioSB** [comment]
Olá,

Fiz uma leve pesquisa a respeito e cheguei a uma conclusão:
O projeto não roda em ambiente Windows porque foi desenvolvido em macOS e/ou Linux.

Quando o desenvolvedor pressiona a tecla "Enter" no macOS ou no Linux o Visual Studio Code entende como "\r" (caractere de escape CR), já quando estamos em Windows é o "\n" (caractere de quebra de linha), se eu ir ao Visual Studio Code e em seu menu inferior, no lado direito trocar de "CRLF" para "LF" os erros de quebra de linha desaparacem, pois o VSCode começa interpretar aquilo como um "\n" e não "\r".

Segue o anexo:
Com erro
![image](https://user-images.githubusercontent.com/34246280/87979996-4db1c080-caa9-11ea-8dbb-36d70819b519.png)

Sem erro
![image](https://user-images.githubusercontent.com/34246280/87980035-5aceaf80-caa9-11ea-9a33-af502c16f7d1.png)

A melhor solução encontrada até agora foi deixar o arquivo .eslintrc.json da seguinte maneira:

```json
{
  "extends": ["prettier/react", "prettier/standard"],
  "parser": "babel-eslint",
  "plugins": ["react", "react-hooks", "import", "prettier", "standard"],
  "rules": {
    "quotes": [2, "single"],
    "semi": [2, "never"],
    "comma-dangle": [2, "never"],
    "no-trailing-spaces": [2],
    "jsx-quotes": ["error", "prefer-single"],
    "react/jsx-boolean-value": [0],
    "react-hooks/rules-of-hooks": "error",
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ],
    "space-before-function-paren": 0
  }
}
```
Onde a única alteração ocorre em `"prettier/prettier"`, esta alteração está tornando o projeto funcional tanto no Windows quanto no Linux, se no macOS não houver divergências acredito que seria a única opção para poder realizar um PR.
É interessante que se for fazer essa alteração, faça uma entrega contínua nos projetos que usa o boilerplate.

**Comment by jpbretanha** [comment]
Show de bola @CaaioSB! Que tal abrir um PR pro nosso boilerplate agora que tu também é de casa? hahahaha
